export const sampleEmployees = [
    {
      id: 1,
      name: "John Doe",
      age: 30,
      division: "Development",
      tasksDone: 5,
      tasksInProgress: 2,
      tasksToDo: 3,
      supervisor: "Alice Smith",
      leaves: 2,
      remarks: "Consistently performs well.",
      imageUrl: "https://via.placeholder.com/150", 
    },
    {
      id: 2,
      name: "Jane Smith",
      age: 28,
      division: "Marketing",
      tasksDone: 4,
      tasksInProgress: 1,
      tasksToDo: 4,
      supervisor: "Bob Johnson",
      leaves: 1,
      remarks: "Great team player.",
      imageUrl: "https://via.placeholder.com/150",
    },
    {
      id: 3,
      name: "Emily Johnson",
      age: 25,
      division: "Sales",
      tasksDone: 6,
      tasksInProgress: 3,
      tasksToDo: 2,
      supervisor: "Charlie Brown",
      leaves: 0,
      remarks: "Excellent communication skills.",
      imageUrl: "https://via.placeholder.com/150",
    },
  ];